{{- if .Values.development }}
apiVersion: v1
kind: Secret
metadata:
  name: lodestar-config-configuration
type: Opaque
stringData:
  RUNTIME_BASE_CONFIG_FILE: "{{ .Values.runtimeBaseConfigFile }}"
  RUNTIME_CONFIG_CHECK_MODIFIED: "{{ .Values.runtimeConfigCheckModified }}"
{{- end }}
