{{- if .Values.development }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  JWT_PUBKICKEY_LOCATION: "{{ .Values.jwtPublicKeyLocation }}"
  JWT_ISSUER: "{{ .Values.jwtIssuer }}"
  JWT_ENABLE: "{{ .Values.jwtEnable }}"
{{- end }}
