name: lodestar-config
development: true

servicePort: 8080

imageName: "lodestar-config"
imageTag: "latest"

builderImage: registry.access.redhat.com/ubi8/openjdk-11
builderImageTag: 1.3

git:
  uri: https://github.com/rht-labs/lodestar-config.git
  ref: master

runtimeConfigs:
  - name: lodestar-runtime
    file: lodestar-runtime-config.yaml
    path: /runtime
  - name: lodestar-runtime-one
    file: lodestar-runtime-config-one.yaml
    path: /runtime
  - name: lodestar-runtime-two
    file: lodestar-runtime-config-two.yaml
    path: /runtime